//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ALRAudjustment
    {
        public int ALRID { get; set; }
        public Nullable<int> MbrID { get; set; }
        public string ALRSavings { get; set; }
        public string AdvanceALR { get; set; }
        public string CrDt { get; set; }
    
        public virtual Loan Loan { get; set; }
        public virtual Member Member { get; set; }
    }
}
