//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Branch
    {
        public int BranchID { get; set; }
        public string BranchCode { get; set; }
        public string BranchName { get; set; }
        public string OpenDate { get; set; }
        public string BAddress { get; set; }
        public string City { get; set; }
        public string State { get; set; }
        public Nullable<int> PinCode { get; set; }
        public Nullable<int> ManagerID { get; set; }
    }
}
