//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class FinGroup
    {
        public int GroupID { get; set; }
        public string GroupCode { get; set; }
        public string BranchCode { get; set; }
        public string Village { get; set; }
        public Nullable<int> Net_Members { get; set; }
        public string CrDt { get; set; }
        public string DOC { get; set; }
        public Nullable<int> Distance { get; set; }
        public string GStatus { get; set; }
        public Nullable<int> StaffID { get; set; }
        public string FormedBy { get; set; }
        public string MeetingPlaceAddress { get; set; }
        public string GType { get; set; }
        public string GrpName { get; set; }
        public string RecoveryDay { get; set; }
    }
}
