//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Loan_Cols
    {
        public int LoanColId { get; set; }
        public Nullable<int> LoanId { get; set; }
        public Nullable<int> MbrId { get; set; }
        public string Collected_Amount { get; set; }
        public string Actual_Balance { get; set; }
        public string Prin_Balance { get; set; }
        public string Int_Collect { get; set; }
        public string Prin_Collected { get; set; }
        public Nullable<int> Balance_Installment { get; set; }
        public string Balance_Interest { get; set; }
        public string Prin_Due { get; set; }
        public string Int_Due { get; set; }
        public string Transact_Date { get; set; }
        public string Next_Due_Date { get; set; }
        public string Upto_Last_Savings { get; set; }
        public string ALRSavings { get; set; }
        public string As_On { get; set; }
        public string Adjustment { get; set; }
        public string PaidEMI { get; set; }
        public string PrePrinAmt { get; set; }
        public string PreInterestAmt { get; set; }
        public string Collect_Or_RefoundAmt { get; set; }
        public string PostedUserID { get; set; }
        public Nullable<int> ArrearsInd { get; set; }
    
        public virtual Loan Loan { get; set; }
        public virtual Member Member { get; set; }
    }
}
