//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public Member()
        {
            this.Loans = new HashSet<Loan>();
            this.Loan_Cols = new HashSet<Loan_Cols>();
            this.ALRAudjustments = new HashSet<ALRAudjustment>();
        }
    
        public int MbrId { get; set; }
        public string MbrName { get; set; }
        public string GroupCode { get; set; }
        public string Husbandname { get; set; }
        public Nullable<int> Age { get; set; }
        public string MbrStatus { get; set; }
        public string WithdrawDt { get; set; }
        public Nullable<int> StaffId { get; set; }
        public string MbrAddress { get; set; }
        public string DOJ { get; set; }
        public string CantactNo { get; set; }
        public string Gender { get; set; }
        public string GrpName { get; set; }
        public string StaffName { get; set; }
        public string Nominee { get; set; }
        public string PhoneNo2 { get; set; }
        public string AdharaCardNum { get; set; }
        public string RCardNo { get; set; }
    
        public virtual ICollection<Loan> Loans { get; set; }
        public virtual ICollection<Loan_Cols> Loan_Cols { get; set; }
        public virtual ICollection<ALRAudjustment> ALRAudjustments { get; set; }
    }
}
