//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.DB
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Objects;
    using System.Data.Objects.DataClasses;
    using System.Linq;
    
    public partial class MicroFinanceEntities : DbContext
    {
        public MicroFinanceEntities()
            : base("name=MicroFinanceEntities")
        {
            // Disable initializer since we're using Database First
            Database.SetInitializer<MicroFinanceEntities>(null);
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            // For Database First approach, we don't need to configure the model
            // The EDMX file handles the model configuration
        }
    
        public DbSet<StaffLogin> StaffLogins { get; set; }
        public DbSet<UserLog> UserLogs { get; set; }
        public DbSet<Branch> Branches { get; set; }
        public DbSet<Staff> Staffs { get; set; }
        public DbSet<Member> Members { get; set; }
        public DbSet<ALRAudjustment> ALRAudjustments { get; set; }
        public DbSet<Loan> Loans { get; set; }
        public DbSet<PartnerDetail> PartnerDetails { get; set; }
        public DbSet<Loan_Cols> Loan_Cols { get; set; }
        public DbSet<TmpLoanColsBackUpData> TmpLoanColsBackUpDatas { get; set; }
        public DbSet<TmpLoansBackUpData> TmpLoansBackUpDatas { get; set; }
        public DbSet<TmpReceipt> TmpReceipts { get; set; }
        public DbSet<TmpSummeryReportData> TmpSummeryReportDatas { get; set; }
        public DbSet<FinGroup> FinGroups { get; set; }
    
        public virtual ObjectResult<spGetLoanDetails_Result> spGetLoanDetails(Nullable<int> loanId, Nullable<int> mbrId)
        {
            var loanIdParameter = loanId.HasValue ?
                new ObjectParameter("LoanId", loanId) :
                new ObjectParameter("LoanId", typeof(int));
    
            var mbrIdParameter = mbrId.HasValue ?
                new ObjectParameter("MbrId", mbrId) :
                new ObjectParameter("MbrId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetLoanDetails_Result>("spGetLoanDetails", loanIdParameter, mbrIdParameter);
        }
    
        public virtual ObjectResult<spGetWithDrawMbrsList_Result> spGetWithDrawMbrsList()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetWithDrawMbrsList_Result>("spGetWithDrawMbrsList");
        }
    
        public virtual int spDeleteBackUpTble()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spDeleteBackUpTble");
        }
    
        public virtual int spTakeBackUpBeforeLoanPost(string nextDueDt)
        {
            var nextDueDtParameter = nextDueDt != null ?
                new ObjectParameter("NextDueDt", nextDueDt) :
                new ObjectParameter("NextDueDt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spTakeBackUpBeforeLoanPost", nextDueDtParameter);
        }
    
        public virtual int spGetProgressReportData(string frmDt, string toDt)
        {
            var frmDtParameter = frmDt != null ?
                new ObjectParameter("FrmDt", frmDt) :
                new ObjectParameter("FrmDt", typeof(string));
    
            var toDtParameter = toDt != null ?
                new ObjectParameter("ToDt", toDt) :
                new ObjectParameter("ToDt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGetProgressReportData", frmDtParameter, toDtParameter);
        }
    
        public virtual int spGetReceiptsAndPaymentsData(string frmDt, string toDt)
        {
            var frmDtParameter = frmDt != null ?
                new ObjectParameter("FrmDt", frmDt) :
                new ObjectParameter("FrmDt", typeof(string));
    
            var toDtParameter = toDt != null ?
                new ObjectParameter("ToDt", toDt) :
                new ObjectParameter("ToDt", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("spGetReceiptsAndPaymentsData", frmDtParameter, toDtParameter);
        }
    
        public virtual ObjectResult<spGetDailyDueReportsData_Result8> spGetDailyDueReportsData(string grpName, string staffName)
        {
            var grpNameParameter = grpName != null ?
                new ObjectParameter("GrpName", grpName) :
                new ObjectParameter("GrpName", typeof(string));
    
            var staffNameParameter = staffName != null ?
                new ObjectParameter("StaffName", staffName) :
                new ObjectParameter("StaffName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetDailyDueReportsData_Result8>("spGetDailyDueReportsData", grpNameParameter, staffNameParameter);
        }
    
        public virtual ObjectResult<spDueAndCollectedAmt_Result1> spDueAndCollectedAmt()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spDueAndCollectedAmt_Result1>("spDueAndCollectedAmt");
        }
    
        public virtual ObjectResult<spGetLoanMbrsList_Result6> spGetLoanMbrsList(string grpName, string staffName, Nullable<int> mbrId)
        {
            var grpNameParameter = grpName != null ?
                new ObjectParameter("GrpName", grpName) :
                new ObjectParameter("GrpName", typeof(string));
    
            var staffNameParameter = staffName != null ?
                new ObjectParameter("StaffName", staffName) :
                new ObjectParameter("StaffName", typeof(string));
    
            var mbrIdParameter = mbrId.HasValue ?
                new ObjectParameter("MbrId", mbrId) :
                new ObjectParameter("MbrId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetLoanMbrsList_Result6>("spGetLoanMbrsList", grpNameParameter, staffNameParameter, mbrIdParameter);
        }
    
        public virtual ObjectResult<spLoansReport_Result> spLoansReport(string grpCode, string staffName)
        {
            var grpCodeParameter = grpCode != null ?
                new ObjectParameter("GrpCode", grpCode) :
                new ObjectParameter("GrpCode", typeof(string));
    
            var staffNameParameter = staffName != null ?
                new ObjectParameter("StaffName", staffName) :
                new ObjectParameter("StaffName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spLoansReport_Result>("spLoansReport", grpCodeParameter, staffNameParameter);
        }
    
        public virtual ObjectResult<spGetLoanMbrsList_Result6> spGetLoanMbrsList1(string grpName, string staffName, Nullable<int> mbrId)
        {
            var grpNameParameter = grpName != null ?
                new ObjectParameter("GrpName", grpName) :
                new ObjectParameter("GrpName", typeof(string));
    
            var staffNameParameter = staffName != null ?
                new ObjectParameter("StaffName", staffName) :
                new ObjectParameter("StaffName", typeof(string));
    
            var mbrIdParameter = mbrId.HasValue ?
                new ObjectParameter("MbrId", mbrId) :
                new ObjectParameter("MbrId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<spGetLoanMbrsList_Result6>("spGetLoanMbrsList1", grpNameParameter, staffNameParameter, mbrIdParameter);
        }
    }
}
