//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class PartnerDetail
    {
        public int PrtnrID { get; set; }
        public string PrtnrName { get; set; }
        public string Address { get; set; }
        public string CatntactNum { get; set; }
        public string City { get; set; }
        public string Statte { get; set; }
        public string ZIP { get; set; }
        public string AdharaCardNum { get; set; }
        public string CrDate { get; set; }
        public string InvestmentAmt { get; set; }
    }
}
