//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.DB
{
    using System;
    
    public partial class spDueAndCollectedAmt_Result1
    {
        public Nullable<int> Total_Due_Amount { get; set; }
        public int CollectedAmount { get; set; }
    }
}
