//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.DB
{
    using System;
    
    public partial class spGetLoanMbrsList_Result5
    {
        public int LoanID { get; set; }
        public int MbrId { get; set; }
        public string MbrName { get; set; }
        public string GrpName { get; set; }
        public string Column1 { get; set; }
        public int Column2 { get; set; }
        public string Column3 { get; set; }
        public string Column4 { get; set; }
        public string Column5 { get; set; }
        public int Column6 { get; set; }
        public Nullable<decimal> Prin_EMI { get; set; }
        public string Next_Due_Date { get; set; }
        public string Column7 { get; set; }
        public string Column8 { get; set; }
    }
}
