//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.DB
{
    using System;
    
    public partial class spGetLoanMbrsList_Result2
    {
        public int LoanID { get; set; }
        public int MbrId { get; set; }
        public string MbrName { get; set; }
        public string GrpName { get; set; }
        public string Actual_Balance { get; set; }
        public Nullable<int> NoOfDay { get; set; }
        public string PaidEMI { get; set; }
        public string Collected_Amount { get; set; }
        public string Balance_Amount { get; set; }
        public Nullable<int> Balance_Installment { get; set; }
        public Nullable<int> Prin_EMI { get; set; }
        public string Next_Due_Date { get; set; }
        public string During_Savings { get; set; }
        public string Savings { get; set; }
    }
}
