//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.DB
{
    using System;
    
    public partial class spGetDailyDueReportsData_Result3
    {
        public string GrpName { get; set; }
        public Nullable<int> Net_Members { get; set; }
        public string CrDt { get; set; }
        public string DOC { get; set; }
        public string Loan_Amount { get; set; }
        public string Balance_Interest { get; set; }
        public string ALRSavings { get; set; }
        public string NetSavings { get; set; }
        public Nullable<int> NoOfDay { get; set; }
        public string Prin_EMI { get; set; }
        public string Int_EMI { get; set; }
    }
}
