//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.DB
{
    using System;
    
    public partial class spSelectSummerReportDta_Result1
    {
        public string Particulars { get; set; }
        public string BOR { get; set; }
        public string Added { get; set; }
        public string Dropped { get; set; }
        public string EOR { get; set; }
    }
}
