//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.DB
{
    using System;
    
    public partial class spSelectReceiptsAndPaymentsReportDta_Result1
    {
        public string Receipts { get; set; }
        public string Rs { get; set; }
    }
}
