//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Staff
    {
        public Staff()
        {
            this.StaffLogins = new HashSet<StaffLogin>();
        }
    
        public int StaffID { get; set; }
        public string StaffName { get; set; }
        public string DOB { get; set; }
        public string DOJ { get; set; }
        public string Status { get; set; }
    
        public virtual ICollection<StaffLogin> StaffLogins { get; set; }
    }
}
