//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class StaffLogin
    {
        public int UsrId { get; set; }
        public Nullable<int> StaffId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public string RolePermission { get; set; }
        public Nullable<int> IsLocked { get; set; }
    
        public virtual Staff Staff { get; set; }
    }
}
