//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpLoansBackUpData
    {
        public int LoanID { get; set; }
        public Nullable<int> MbrId { get; set; }
        public string Loan_Amount { get; set; }
        public string Balance_Amount { get; set; }
        public string RateOfInterest { get; set; }
        public string Prin_EMI { get; set; }
        public string Int_EMI { get; set; }
        public Nullable<int> NoOfDay { get; set; }
        public string Date_Of_Disbursement { get; set; }
        public string Expiry_Date { get; set; }
        public string ALRSavings { get; set; }
        public string GRFAmt { get; set; }
        public string Processing_Fee { get; set; }
        public Nullable<int> Stationary { get; set; }
        public Nullable<int> Insurance { get; set; }
        public string Other_Income { get; set; }
        public string NetSavings { get; set; }
        public string GrpCode { get; set; }
        public string StaffName { get; set; }
        public string NextDueDt { get; set; }
        public string Balance_Interest { get; set; }
        public string LoanType { get; set; }
    }
}
