//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class TmpSummeryReportData
    {
        public int SlNo { get; set; }
        public string Particulars { get; set; }
        public string BOR { get; set; }
        public string Added { get; set; }
        public string Dropped { get; set; }
        public string EOR { get; set; }
    }
}
