//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestApp.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserLog
    {
        public int LogId { get; set; }
        public string LoginName { get; set; }
        public Nullable<System.DateTime> LogInDateTime { get; set; }
        public Nullable<System.DateTime> LogOutDateTime { get; set; }
        public string StaffName { get; set; }
    }
}
